FROM python:3.8
WORKDIR /usr/src/app
COPY Pipfile .
COPY Pipfile.lock .
RUN pip install pipenv
RUN pipenv lock -r > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./Bulk .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]